### ISSUE TITLE
Ability to copy quarters selections

### ISSUE THREAD

**Issue by Stoatii** [jwkerr/Quarters#10]
**Is your feature request related to a problem? Please describe.**
If players have complex stacked buildings (non square apartment buildings) they have to spend a lot of time repeating the same arrangement of cuboids in every room on every floor.

**Describe the solution you'd like**
I think it would benefit players with intricate but repetitive buildings (containing 2 or more cuboids in a single apartment) to have the ability to copy quarter selections. The selection would be copied using the position of the player as the datum point. Therefore, in apartments of the same style the player would simply have to go to the same position in each apartment (after having copied the first apartment's cuboid arrangement) and just paste it.

**Comment by jwkerr** [comment]
i plan to add this in the v1 update i'm working on rn

**Comment by jwkerr** [comment]
done, will be in v1, here's a screenshot of me messing around with it

![2024-08-16_11 32 34](https://github.com/user-attachments/assets/e76a7054-4197-41e5-8b17-29beee9621c9)
