### ISSUE TITLE
The ability to do /q create without /q selection add

### ISSUE THREAD

**Issue by ltown1** [jwkerr/Quarters#12]
**Is your feature request related to a problem? Please describe.**
It isn't. Just a simple quality of life thing.

**Describe the solution you'd like**
The ability to do /q create skipping /q selection add. I think that explains it all

**Comment by jwkerr** [comment]
working on v1, this will be added

**Comment by jwkerr** [comment]
turns out i already added this while cleaning up commands but forgot, it will be in v1
