### ISSUE TITLE
Hierarchy levels & Quarter list

### ISSUE THREAD

**Issue by M8E-ya** [jwkerr/Quarters#13]
**Hierarchy Levels**

In the plugin we have several quarter types but my main focus is for Public, Commons and Worksite, these on their own are great but if a town has several of them then it gets a bit complicated as you would then instead want to make quarters and claim them yourself first and then trust the players to it, I think we could fix this issue by a hierarchy level system, this simply put means the mayor and comayor can provide/promote a town member to a certain level and also set level requirements check for quarters. 

This is practice means a town can have several Public, Commons and Worksite quarters with different permission levels. a player with level 1 access will not be able to use level 3 quarters but a level 3 player can use any on their level or below, (mayor, comayor and planner are the highest level by default but only mayor and comayor can promote player levels).

**Quarter list**

This is more of a quality of life suggestion but it would be great if mayor, comayor and planner can do /q list and /q list claimed/unclaimed within the town to find all the quarters and who's their owner and where they are located.

**Comment by jwkerr** [comment]
hello, i have decided to not go forward with adding this for the upcoming v1 release, however i have added many new features that can help achieve similar results such as much finer permission management similar to towns, nations and plots as well as the ability to set the owner of a quarter without them being online to claim it
