### ISSUE TITLE
The ability to edit an existing quarter

### ISSUE THREAD

**Issue by E-Turcios** [jwkerr/Quarters#16]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.
Whenever I create a quarter, it is permanent. There is no way to add on or remove cuboids to any existing quarter. This is a problem if I mess up and forget to add sections to a door or allow underground access. Having the ability to edit and existing quarter will solve this problem.

**Describe the solution you'd like**
/q edit

This command will allow the mayor to edit any existing quarter created in the town. Allowing the mayor to add or remove cuboids to the quarter again.

**Comment by jwkerr** [comment]
added in https://github.com/jwkerr/Quarters/commit/2f573a6cbbc8f001a23fdcb24fed6b6a71a54232 as `/q edit addselection` and `/q edit remove`
