### ISSUE TITLE
Quarter metadata

### ISSUE THREAD

**Issue by galacticwarrior9** [jwkerr/Quarters#22]
**Is your feature request related to a problem? Please describe.**
It is not possible to save custom metadata to a quarter. This makes it difficult for add-on plugins to implement features such as that proposed in #9.

**Describe the solution you'd like**
A method of saving metadata to a quarter. It would be ideal if `Quarter` implemented `TownyObject` so that Towny's `MetadataUtil` methods work with it.

**Comment by jwkerr** [comment]
I did think about this but since they themselves are stored in metadata I thought it might be a bit strange

I will look into it though and either do that or add a similar alternative maybe

**Comment by jwkerr** [comment]
working on making Quarter extend TownyObject right now, but might take a bit to make sure its working well, looks like i will have to write some custom typeadapter stuff for metadata fields

**Comment by jwkerr** [comment]
merged but will be in an update after some other changes/additions
