### ISSUE TITLE
Issue with setting itemuse permissions 

### ISSUE THREAD

**Issue by galacticwarrior9** [jwkerr/Quarters#30]
**Describe the bug**
It is not possible to set `itemuse` permissions for quarters using the tab-completed `/quarters set perm` command. This is because the `ActionType` enum value is `ITEM_USE`, but the tab-completed argument in `/quarters set perm` is `itemuse`. This triggers an `IllegalArgumentException` here: https://github.com/jwkerr/Quarters/blob/508fe9255b888470d5625bd37a0c867d9f2e5522/src/main/java/au/lupine/quarters/command/quarters/method/set/SetPermMethod.java#L28

**To Reproduce**
Execute `/quarters set perm itemuse resident true`.

The command works if you change `itemuse` to `item_use`. 

**Expected behavior**
Either the tab-completion returns `item_use`, or the `ActionType` enum value changes to `ITEMUSE`.

**Version**
Quarters version: 1.0.5
Towny version: 0.100.3.13

**Comment by jwkerr** [comment]
I'll fix this tomorrow

**Comment by jwkerr** [comment]
https://modrinth.com/plugin/quarters/version/iNDTX3px should be fixed in 1.0.6
