### ISSUE TITLE
Rentable Quarters

### ISSUE THREAD

**Issue by MegalithOfficial** [jwkerr/Quarters#9]
**Is your feature request related to a problem? Please describe.**
Players currently lack engaging in-game economic opportunities and consequences for financial decisions.

**Describe the solution you'd like**
Introduce a feature enabling players to create rentable spaces in the game. For example, I could set up a shop, and others could rent it for 10 bucks a week or 50 bucks a month, fostering interactive virtual commerce. Implementing eviction consequences for players unable to meet rent payments, adding realism and accountability to in-game financial commitments.

**Comment by Fruitloopins** [comment]
this is something I have on the GitHub project for quarters already, but it probably won't come anytime soon due to the nature of how I setup the plugin using metadata

adding new properties to quarters would break all quarters on "legacy" servers without some sort of porting system, which I could make but I fear it would break servers' quarters installs if it bugs

**Comment by MegalithOfficial** [comment]
perhaps implementing a translator to automatically update metadata to the new data setup before server activation. Alternatively, incorporate a default options feature, enabling the system to use predefined settings (e.g., false) if the metadata lacks a specific option.

**Comment by Fruitloopins** [comment]
its possible but not something i have any motivation to do right now, it will probably take a 1.0 breaking release in the future or someone willing to pay for the development of a porting system so more features can be added

**Comment by Colt44Magnum** [comment]
How much

**Comment by Fruitloopins** [comment]
I would have to think about how I would implement it first

**Comment by jwkerr** [comment]
hello, i'm sorry to say but i do not intend to add this into mainstream quarters right now, i don't know if you play on earthmc (the server quarters is designed for) or another one, but i would recommend trying to get it added as an addon plugin instead once v1 is released and i've written documentation for it

i would be willing to help out with how to put that together and add api features if needed etc. if anyone wants to pursue that
